USE test;
DROP TABLE IF EXISTS parts;
CREATE TABLE parts( ID INT(11) NOT NULL AUTO_INCREMENT,
  PART_NAME VARCHAR(255) NOT NULL,
  PART_BASE TINYINT(4) NOT NULL,
  PART_VALUE INT(11) NOT NULL,
  PRIMARY KEY (ID)) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8;
INSERT INTO parts (PART_NAME, PART_BASE, PART_VALUE) VALUES ('Материнская плата', 1, 16);
INSERT INTO parts (PART_NAME, PART_BASE, PART_VALUE) VALUES ('Процессор', 1, 15);
INSERT INTO parts (PART_NAME, PART_BASE, PART_VALUE) VALUES ('Оперативная память 2Гб', 1, 10);
INSERT INTO parts (PART_NAME, PART_BASE, PART_VALUE) VALUES ('Оперативная память 4Гб', 1, 8);
INSERT INTO parts (PART_NAME, PART_BASE, PART_VALUE) VALUES ('Оперативная память 8Гб', 1, 4);
INSERT INTO parts (PART_NAME, PART_BASE, PART_VALUE) VALUES ('Кулер', 1, 20);
INSERT INTO parts (PART_NAME, PART_BASE, PART_VALUE) VALUES ('Видео карта 2Гб', 0, 4);
INSERT INTO parts (PART_NAME, PART_BASE, PART_VALUE) VALUES ('Видео карта 4Гб', 0, 4);
INSERT INTO parts (PART_NAME, PART_BASE, PART_VALUE) VALUES ('Звуковая карта', 0, 6);
INSERT INTO parts (PART_NAME, PART_BASE, PART_VALUE) VALUES ('Материнская плата', 1, 16);
INSERT INTO parts (PART_NAME, PART_BASE, PART_VALUE) VALUES ('Плата видеозахвата', 0, 2);
INSERT INTO parts (PART_NAME, PART_BASE, PART_VALUE) VALUES ('Плата расширения SATA', 0, 3);
INSERT INTO parts (PART_NAME, PART_BASE, PART_VALUE) VALUES ('Блок питания ATX', 1, 20);
INSERT INTO parts (PART_NAME, PART_BASE, PART_VALUE) VALUES ('Корпус блока', 1, 14);
INSERT INTO parts (PART_NAME, PART_BASE, PART_VALUE) VALUES ('Привод DVD дисков', 0, 8);
INSERT INTO parts (PART_NAME, PART_BASE, PART_VALUE) VALUES ('Привод BD-ray', 0, 2);
INSERT INTO parts (PART_NAME, PART_BASE, PART_VALUE) VALUES ('HDD 500Гб', 1, 10);
INSERT INTO parts (PART_NAME, PART_BASE, PART_VALUE) VALUES ('HDD 1Тб', 1, 8);
INSERT INTO parts (PART_NAME, PART_BASE, PART_VALUE) VALUES ('SSD 250Гб', 1, 9);
INSERT INTO parts (PART_NAME, PART_BASE, PART_VALUE) VALUES ('SSD 500Гб', 1, 16);
INSERT INTO parts (PART_NAME, PART_BASE, PART_VALUE) VALUES ('Монитор 19"', 1, 6);
INSERT INTO parts (PART_NAME, PART_BASE, PART_VALUE) VALUES ('Монитор 21"', 1, 5);
INSERT INTO parts (PART_NAME, PART_BASE, PART_VALUE) VALUES ('Монитор 29"', 1, 2);
INSERT INTO parts (PART_NAME, PART_BASE, PART_VALUE) VALUES ('Клавиатура', 1, 20);
INSERT INTO parts (PART_NAME, PART_BASE, PART_VALUE) VALUES ('Мышь', 1, 22);
INSERT INTO parts (PART_NAME, PART_BASE, PART_VALUE) VALUES ('Web камера', 0, 8);
INSERT INTO parts (PART_NAME, PART_BASE, PART_VALUE) VALUES ('USB FlashCard 8Гб', 0, 7);
INSERT INTO parts (PART_NAME, PART_BASE, PART_VALUE) VALUES ('USB FlashCard 16Гб', 0, 6);
INSERT INTO parts (PART_NAME, PART_BASE, PART_VALUE) VALUES ('USB FlashCard 64Гб', 0, 3);
INSERT INTO parts (PART_NAME, PART_BASE, PART_VALUE) VALUES ('Кабель HDMI 1.8м', 0, 4);
INSERT INTO parts (PART_NAME, PART_BASE, PART_VALUE) VALUES ('Кабель DVI 1.8м', 0, 4);
INSERT INTO parts (PART_NAME, PART_BASE, PART_VALUE) VALUES ('Кабель VGA 1.8м', 0, 2);
